### ISSUE TITLE
make log statements easy to find

### ISSUE THREAD

**Issue by max-mapper** [sethvincent/appa#2]
it took me forever to figure out the stdout was coming from here https://github.com/sethvincent/appa/blob/ec99078c33c4d6b8208ac635138aa8656889483e/index.js#L60

maybe we should disable logging by default (unix rule of silence etc)?

btw workaround is to do this: `var app = createApp({log: {level: 'silent'}})`

**Comment by sethvincent** [comment]
I decided to keep the default at `{ log: { level: 'info' } }` because I almost always want that (maybe the one situation where I feel like it makes sense to ignore the rule of silence).

But! I made it easier to disable logging: `var app = createApp({ log: false })`, and added docs for that in the readme and [api docs](https://github.com/sethvincent/appa/blob/master/docs/api.md)
